global:
  name:
    appName: mysql
    appLabel:
      app: mysql
      environment: prod
  replicaCount: 1
  containers:
   -  name: mysql
      image: mysql
      tag: "8.0"
      pullPolicy: Always
      # command:
      #   - "--default-authentication-plugin=mysql_native_password"
      ports:
       - name: client
         port: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "test"
        - name: MYSQL_DATABASE
          value: employeedb
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "no"

      resources:
        limits:
          memory: "1Gi"
          cpu: "1"
        requests:
          memory: "1Gi"
          cpu: "0.5"
      livenessProbe:
        tcpSocket:
           port: 3306
      readinessProbe:
        tcpSocket:
          port: 3306

      volumeMounts:
      - name: empty-dir
        mountPath: /etc/touch
      

  affinity:
    podAntiAffinity:
      weight: 100
      key: app
      values:
      - mysql
      topologyKey: kubernetes.io/hostname
  service:
    type: ClusterIP
    headless: false
    ports:
      - port: 3306
        targetPort: 3306
  volumes:
    - name: empty-dir
      hostPath:
         path: {}
